---
title: 'The Hypermynds Employee Handbook'
author: 'The Hypermynds Team'
date: "`r format(Sys.Date(), '%d/%m/%Y')`"
---

# The Hypermynds Employee Handbook {-}

Welcome to Hypermynds.

This handbook is the primary reference for anyone working at Hypermynds.  
Its goal is to make every team member able to work **effectively, safely and independently** in a company that operates complex technology in regulated energy markets.

Here you will find:

- practical information on how to set up and use your work tools  
- rules and processes that govern daily work  
- guidelines on how we build, deploy and operate our software  
- references on how we interact with colleagues, customers and partners  

The handbook is a **living document**: it evolves together with the company.  
Whenever something is unclear, missing or outdated, improving this handbook is considered part of everyone’s responsibility.

If you would like to contribute:

- you can propose a change via a [Pull Request](https://github.com/hypermynds/handbook/pulls)  
- or suggest new content by opening an [Issue](https://github.com/hypermynds/handbook/issues)  

Keeping this handbook accurate and up to date is one of the ways we make Hypermynds a place where people can do their best work.
