# Security and privacy

## Set up two-factor authentication

Two-factor authentication (2FA) is an extra layer of security that helps to protect
your accounts, even if someone else finds your password. There are multiple
options for 2FA including:

* a time-based token generated by an *authenticator application*;
* a *text message* with a temporary token sent to your mobile phone.

The preferred 2FA method is time-based token generated by an authenticator
application and it is **mandatory** to setup 2FA on your accounts on *Google*,
[*GitHub*](https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication),
[*Slack*](https://slack.com/help/articles/204509068-Set-up-two-factor-authentication#authentication-app-1)
and *AWS*.

Text message with token sent to your mobile phone is not recommended due to
vulnerabilities, unless it is the only available method.

### Download and install an authentication app

Before to set up 2FA on your accounts you need to install an authentication
application on your devices, here a few options:

* **Android**: [Authy](https://play.google.com/store/apps/details?id=com.authy.authy),
  [Google Authenticator](https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2) and [Microsoft Authenticator](https://play.google.com/store/apps/details?id=com.azure.authenticator)
* **macOS**: [Authy](https://authy.com/) (`brew install authy`)
